<?php
include_once('models/pais.php');
fORM::mapClassToTable('Pais', 'pais');
include_once('models/atividade.php');
fORM::mapClassToTable('Atividade', 'atividade');
include_once('models/auditoria.php');
fORM::mapClassToTable('Auditoria', 'auditoria');
include_once('models/beneficiario.php');
fORM::mapClassToTable('Beneficiario', 'beneficiario');
include_once('models/caixa.php');
fORM::mapClassToTable('Caixa', 'caixa');
include_once('models/contribuicao.php');
fORM::mapClassToTable('Contribuicao', 'contribuicao');
include_once('models/Documento.php');
fORM::mapClassToTable('Documento', 'documento');
include_once('models/endereco.php');
fORM::mapClassToTable('Endereco', 'endereco');
include_once('models/entidade.php');
fORM::mapClassToTable('Entidade', 'entidade');
include_once('models/entidade_pessoa.php');
fORM::mapClassToTable('EntidadePessoa', 'entidade_pessoa');
include_once('models/estado_civil.php');
fORM::mapClassToTable('EstadoCivil', 'estado_civil');
include_once('models/forma_pagamento.php');
fORM::mapClassToTable('FormaPagamento', 'forma_pagamento');
include_once('models/log_bairro.php');
fORM::mapClassToTable('LogBairro', 'log_bairro');
include_once('models/log_controle.php');
fORM::mapClassToTable('LogControle', 'log_controle');
include_once('models/log_cpc.php');
fORM::mapClassToTable('LogCpc', 'log_cpc');
include_once('models/log_faixa_bairro.php');
fORM::mapClassToTable('LogFaixaBairro', 'log_faixa_bairro');
include_once('models/log_faixa_cpc.php');
fORM::mapClassToTable('LogFaixaCpc', 'log_faixa_cpc');
include_once('models/log_faixa_localidade.php');
fORM::mapClassToTable('LogFaixaLocalidade', 'log_faixa_localidade');
include_once('models/log_faixa_uf.php');
fORM::mapClassToTable('LogFaixaUf', 'log_faixa_uf');
include_once('models/log_faixa_uop.php');
fORM::mapClassToTable('LogFaixaUop', 'log_faixa_uop');
include_once('models/log_grande_usuario.php');
fORM::mapClassToTable('LogGrandeUsuario', 'log_grande_usuario');
include_once('models/log_localidade.php');
fORM::mapClassToTable('LogLocalidade', 'log_localidade');
include_once('models/log_logradouro.php');
fORM::mapClassToTable('LogLogradouro', 'log_logradouro');
include_once('models/log_tipo_logr.php');
fORM::mapClassToTable('LogTipoLogr', 'log_tipo_logr');
include_once('models/log_unid_oper.php');
fORM::mapClassToTable('LogUnidOper', 'log_unid_oper');
include_once('models/motivo_bloqueio.php');
fORM::mapClassToTable('MotivoBloqueio', 'motivo_bloqueio');
include_once('models/pais.php');
fORM::mapClassToTable('Pais', 'pais');
include_once('models/papel.php');
fORM::mapClassToTable('Papel', 'papel');
include_once('models/papel_atividade.php');
fORM::mapClassToTable('PapelAtividade', 'papel_atividade');
include_once('models/papel_pessoa.php');
fORM::mapClassToTable('PapelPessoa', 'papel_pessoa');
include_once('models/parentesco.php');
fORM::mapClassToTable('Parentesco', 'parentesco');
include_once('models/pessoa.php');
fORM::mapClassToTable('Pessoa', 'pessoa');
include_once('models/situacao.php');
fORM::mapClassToTable('Situacao', 'situacao');
include_once('models/telefone.php');
fORM::mapClassToTable('Telefone', 'telefone');
include_once('models/tipo_beneficiario.php');
fORM::mapClassToTable('TipoBeneficiario', 'tipo_beneficiario');
include_once('models/tipo_conta.php');
fORM::mapClassToTable('TipoConta', 'tipo_conta');
include_once('models/tipo_documento.php');
fORM::mapClassToTable('TipoDocumento', 'tipo_documento');
include_once('models/tipo_endereco.php');
fORM::mapClassToTable('TipoEndereco', 'tipo_endereco');
include_once('models/tipo_entidade.php');
fORM::mapClassToTable('TipoEntidade', 'tipo_entidade');
include_once('models/tipo_pessoa.php');
fORM::mapClassToTable('TipoPessoa', 'tipo_pessoa');
include_once('models/tipo_telefone.php');
fORM::mapClassToTable('TipoTelefone', 'tipo_telefone');
include_once('models/plano_unidade_armazenagem.php');
fORM::mapClassToTable('PlanoUnidadeArmazenagem', 'plano_unidade_armazenagem');
include_once('models/periodicidade_cobranca.php');
fORM::mapClassToTable('PeriodicidadeCobranca', 'periodicidade_cobranca');
include_once('models/tipo_unidade_armazenagem.php');
fORM::mapClassToTable('TipoUnidadeArmazenagem', 'tipo_unidade_armazenagem');
include_once('models/tipo_concessao.php');
fORM::mapClassToTable('TipoConcessao', 'tipo_concessao');
include_once('models/status_gaveta.php');
fORM::mapClassToTable('StatusGaveta', 'status_gaveta');
include_once('models/funeraria.php');
fORM::mapClassToTable('Funeraria', 'funeraria');
include_once('models/causa_mortis.php');
fORM::mapClassToTable('CausaMortis', 'causa_mortis');
include_once('models/quadra.php');
fORM::mapClassToTable('Quadra', 'quadra');
include_once('models/lote.php');
fORM::mapClassToTable('Lote', 'lote');
include_once('models/unidade_armazenagem.php');
fORM::mapClassToTable('UnidadeArmazenagem', 'unidade_armazenagem');
include_once('models/unidade_armazenagem_movimentacao.php');
fORM::mapClassToTable('UnidadeArmazenagemMovimentacao', 'unidade_armazenagem_movimentacao');
include_once('models/unidade_armazenagem_pessoa.php');
fORM::mapClassToTable('UnidadeArmazenagemPessoa', 'unidade_armazenagem_pessoa');
include_once('models/gaveta.php');
fORM::mapClassToTable('Gaveta', 'gaveta');
include_once('models/falecido.php');
fORM::mapClassToTable('Falecido', 'falecido');
include_once('models/teste.php');
fORM::mapClassToTable('Teste', 'teste');
include_once('models/pessoa_socio.php');
fORM::mapClassToTable('PessoaSocio', 'pessoa_socio');
include_once('models/campanha.php');
fORM::mapClassToTable('Campanha', 'campanha');
include_once('models/fonte_captacao.php');
fORM::mapClassToTable('FonteCaptacao', 'fonte_captacao');	
include_once('models/campanha_pessoa.php');
fORM::mapClassToTable('CampanhaPessoa', 'campanha_pessoa');	
include_once('models/departamento.php');
fORM::mapClassToTable('Departamento', 'departamento');	
include_once('models/evento.php');
fORM::mapClassToTable('Evento', 'evento');	
include_once('models/evento_agenda.php');
fORM::mapClassToTable('EventoAgenda', 'evento_agenda');	
include_once('models/evento_ata.php');
fORM::mapClassToTable('EventoAta', 'evento_ata');	
include_once('models/evento_pessoa.php');
fORM::mapClassToTable('EventoPessoa', 'evento_pessoa');								
include_once('models/categoria_naoassociado.php');
fORM::mapClassToTable('CategoriaNaoassociado', 'categoria_naoassociado');	
include_once('models/tipo_evento.php');
fORM::mapClassToTable('TipoEvento', 'tipo_evento');	
include_once('models/pessoa_tipo_evento.php');
fORM::mapClassToTable('PessoaTipoEvento', 'pessoa_tipo_evento');
include_once('models/departamento_pessoa.php');
fORM::mapClassToTable('DepartamentoPessoa', 'departamento_pessoa');		
include_once('models/lista.php');
fORM::mapClassToTable('Lista', 'lista');
include_once('models/lista_pessoa.php');
fORM::mapClassToTable('ListaPessoa', 'lista_pessoa');
include_once('models/tipo_lancamento.php');
fORM::mapClassToTable('TipoLancamento', 'tipo_lancamento');	
include_once('models/banco.php');
fORM::mapClassToTable('Banco', 'banco');
include_once('models/categoria.php');
fORM::mapClassToTable('Categoria', 'categoria');		
include_once('models/conta_bancaria.php');
fORM::mapClassToTable('ContaBancaria', 'conta_bancaria');	
include_once('models/documento_caixa.php');
fORM::mapClassToTable('DocumentoCaixa', 'documento_caixa');
include_once('models/variavel.php');
fORM::mapClassToTable('Variavel', 'variavel');
include_once('models/modelo_documento.php');
fORM::mapClassToTable('ModeloDocumento', 'modelo_documento');
include_once('models/template.php');
fORM::mapClassToTable('Template', 'template');
include_once('models/tipo_fornecedor.php');	
fORM::mapClassToTable('TipoFornecedor', 'tipo_fornecedor');		
include_once('models/evento_lista.php');
fORM::mapClassToTable('EventoLista', 'evento_lista');		
include_once('models/evento_inscricao.php');
fORM::mapClassToTable('EventoInscricao', 'evento_inscricao');								
include_once('models/evento_frequencia.php');
fORM::mapClassToTable('EventoFrequencia', 'evento_frequencia');
include_once('models/grupo_bens.php');
fORM::mapClassToTable('GrupoBens', 'grupo_bens');
include_once('models/unidade_medida.php');
fORM::mapClassToTable('UnidadeMedida', 'unidade_medida');	
include_once('models/fabricante.php');
fORM::mapClassToTable('Fabricante', 'fabricante');
include_once('models/marca.php');
fORM::mapClassToTable('Marca', 'marca');	
include_once('models/localidade_bens.php');
fORM::mapClassToTable('LocalidadeBens', 'localidade_bens');	
include_once('models/estado_conservacao.php');
fORM::mapClassToTable('EstadoConservacao', 'estado_conservacao');	
include_once('models/situacao_economica.php');
fORM::mapClassToTable('SituacaoEconomica', 'situacao_economica');
include_once('models/bens.php');
fORM::mapClassToTable('Bens', 'bens');	
include_once('models/status_bem.php');
fORM::mapClassToTable('StatusBem', 'status_bem');	
include_once('models/seguro_bens.php');
fORM::mapClassToTable('SeguroBens', 'seguro_bens');	
include_once('models/seguradora.php');
fORM::mapClassToTable('Seguradora', 'seguradora');
include_once('models/procedencia.php');
fORM::mapClassToTable('Procedencia', 'procedencia');
include_once('models/forma_aquisicao.php');
fORM::mapClassToTable('FormaAquisicao', 'forma_aquisicao');	
include_once('models/bens_movimentacao.php');
fORM::mapClassToTable('BensMovimentacao', 'bens_movimentacao');			
include_once('models/departamento_funcionario.php');
fORM::mapClassToTable('DepartamentoFuncionario', 'departamento_funcionario');
include_once('models/centro_custo.php');
fORM::mapClassToTable('CentroCusto', 'centro_custo');
include_once('models/movimentacao_doacao.php');
fORM::mapClassToTable('MovimentacaoDoacao', 'movimentacao_doacao');			
include_once('models/doacao.php');
fORM::mapClassToTable('Doacao', 'doacao');		
include_once('models/local_armazenamento_doacao.php');
fORM::mapClassToTable('LocalArmazenamentoDoacao', 'local_armazenamento_doacao');		
include_once('models/tipo_doacao.php');
fORM::mapClassToTable('TipoDoacao', 'tipo_doacao');		
include_once('models/programa_doacao.php');
fORM::mapClassToTable('ProgramaDoacao', 'programa_doacao');		
include_once('models/status_doacao.php');
fORM::mapClassToTable('StatusDoacao', 'status_doacao');		
include_once('models/bordero_status.php');
fORM::mapClassToTable('BorderoStatus', 'bordero_status');		
include_once('models/bordero.php');
fORM::mapClassToTable('Bordero', 'bordero');		
include_once('models/bordero_itens.php');
fORM::mapClassToTable('BorderoItens', 'bordero_itens');	
include_once('models/situacao_pedido.php');
fORM::mapClassToTable('SituacaoPedido', 'situacao_pedido');	
include_once('models/situacao_cotacao_compra.php');
fORM::mapClassToTable('SituacaoCotacaoCompra', 'situacao_cotacao_compra');	
include_once('models/produtos_servicos.php');
fORM::mapClassToTable('ProdutosServicos', 'produtos_servicos');	
include_once('models/produtos_servicos_fornecedor.php');
fORM::mapClassToTable('ProdutosServicosFornecedor', 'produtos_servicos_fornecedor');	
include_once('models/pedido.php');
fORM::mapClassToTable('Pedido', 'pedido');	
include_once('models/pedido_itens.php');
fORM::mapClassToTable('PedidoItens', 'pedido_itens');	
include_once('models/cotacao_compra.php');
fORM::mapClassToTable('CotacaoCompra', 'cotacao_compra');	
include_once('models/cotacao_compra_itens.php');
fORM::mapClassToTable('CotacaoCompraItens', 'cotacao_compra_itens');	
include_once('models/cotacao_compra_itens_fornecedor.php');
fORM::mapClassToTable('CotacaoCompraItensFornecedor', 'cotacao_compra_itens_fornecedor');
include_once('models/familia.php');
fORM::mapClassToTable('Familia', 'familia');
include_once('models/item_departamento.php');
fORM::mapClassToTable('ItemDepartamento', 'item_departamento');
include_once('models/quadro_associativo.php');
fORM::mapClassToTable('QuadroAssociativo', 'quadro_associativo');
include_once('models/quadro_associativo_pessoa.php');
fORM::mapClassToTable('QuadroAssociativoPessoa', 'quadro_associativo_pessoa');
include_once('models/cargo.php');
fORM::mapClassToTable('Cargo', 'cargo');
include_once('models/estoque.php');
fORM::mapClassToTable('Estoque', 'estoque');
include_once('models/tipo_necessidades_especiais.php');
fORM::mapClassToTable('TipoNecessidadesEspeciais', 'tipo_necessidades_especiais');
include_once('models/pessoa_tipo_necessidades_especiais.php');
fORM::mapClassToTable('PessoaTipoNecessidadesEspeciais', 'pessoa_tipo_necessidades_especiais');
include_once('models/tipo_contato.php');
fORM::mapClassToTable('TipoContato', 'tipo_contato');
include_once('models/pessoa_tipo_contato.php');
fORM::mapClassToTable('PessoaTipoContato', 'pessoa_tipo_contato');
include_once('models/grupo_ocorrencia.php');
fORM::mapClassToTable('GrupoOcorrencia', 'grupo_ocorrencia');
include_once('models/tipo_ocorrencia.php');
fORM::mapClassToTable('TipoOcorrencia', 'tipo_ocorrencia');
include_once('models/grupo_sanguineo.php');
fORM::mapClassToTable('GrupoSanguineo', 'grupo_sanguineo');
include_once('models/pessoa_dados_medico.php');
fORM::mapClassToTable('PessoaDadosMedico', 'pessoa_dados_medico');
include_once('models/religiao.php');
fORM::mapClassToTable('Religiao', 'religiao');
include_once('models/orgao_emissor.php');
fORM::mapClassToTable('OrgaoEmissor', 'orgao_emissor');
include_once('models/tipo_responsavel.php');
fORM::mapClassToTable('TipoResponsavel', 'tipo_responsavel');
include_once('models/responsavel_aluno.php');
fORM::mapClassToTable('ResponsavelAluno', 'responsavel_aluno');
include_once('models/tipo_bloqueio.php');
fORM::mapClassToTable('TipoBloqueio', 'tipo_bloqueio');
include_once('models/ciclo.php');
fORM::mapClassToTable('Ciclo', 'ciclo');
include_once('models/texto_grupo_ocorrencia.php');
fORM::mapClassToTable('TextoGrupoOcorrencia', 'texto_grupo_ocorrencia');
include_once('models/etapa.php');
fORM::mapClassToTable('Etapa', 'etapa');
include_once('models/situacao_etapa.php');
fORM::mapClassToTable('SituacaoEtapa', 'situacao_etapa');
include_once('models/medicamento.php');
fORM::mapClassToTable('Medicamento', 'medicamento');
include_once('models/vacina.php');
fORM::mapClassToTable('Vacina', 'vacina');
include_once('models/feriado.php');
fORM::mapClassToTable('Feriado', 'feriado');
include_once('models/moeda.php');
fORM::mapClassToTable('Moeda', 'moeda');
include_once('models/forma_tratamento.php');
fORM::mapClassToTable('FormaTratamento', 'forma_tratamento');
include_once('models/disciplina.php');
fORM::mapClassToTable('Disciplina', 'disciplina');
include_once('models/periodo_aula.php');
fORM::mapClassToTable('PeriodoAula', 'periodo_aula');
include_once('models/doenca.php');
fORM::mapClassToTable('Doenca', 'doenca');
include_once('models/convenio.php');
fORM::mapClassToTable('Convenio', 'convenio');	
include_once('models/pessoa_laudo.php');
fORM::mapClassToTable('PessoaLaudo', 'pessoa_laudo');
include_once('models/tipo_funcionario.php');
fORM::mapClassToTable('TipoFuncionario', 'tipo_funcionario');
include_once('models/pessoa_contato.php');
fORM::mapClassToTable('PessoaContato', 'pessoa_contato');
include_once('models/funcao.php');
fORM::mapClassToTable('Funcao', 'funcao');
include_once('models/estabelecimento.php');
fORM::mapClassToTable('Estabelecimento', 'estabelecimento');
include_once('models/tipo_informativo.php');
fORM::mapClassToTable('TipoInformativo', 'tipo_informativo');
include_once('models/evento_informativo.php');
fORM::mapClassToTable('EventoInformativo', 'evento_informativo');
include_once('models/faixa.php');
fORM::mapClassToTable('Faixa', 'faixa');
include_once('models/cor_raca.php');
fORM::mapClassToTable('CorRaca', 'cor_raca');
include_once('models/origem.php');
fORM::mapClassToTable('Origem', 'origem');
include_once('models/horario.php');
fORM::mapClassToTable('Horario', 'horario');
include_once('models/turma.php');
fORM::mapClassToTable('Turma', 'turma');
include_once('models/tipo_disciplina_curso.php');
fORM::mapClassToTable('TipoDisciplinaCurso', 'tipo_disciplina_curso');
include_once('models/tipo_curso.php');
fORM::mapClassToTable('TipoCurso', 'tipo_curso');
include_once('models/curso.php');
fORM::mapClassToTable('Curso', 'curso');
include_once('models/curso_professor.php');
fORM::mapClassToTable('CursoProfessor', 'curso_professor');
include_once('models/lista_documento.php');
fORM::mapClassToTable('ListaDocumento', 'lista_documento');
include_once('models/pessoa_documento_pendente.php');
fORM::mapClassToTable('PessoaDocumentoPendente', 'pessoa_documento_pendente');
include_once('models/pessoa_ocorrencia.php');
fORM::mapClassToTable('PessoaOcorrencia', 'pessoa_ocorrencia');
include_once('models/recorrencia.php');
fORM::mapClassToTable('Recorrencia', 'recorrencia');
include_once('models/evento_recorrente.php');
fORM::mapClassToTable('EventoRecorrente', 'evento_recorrente');
include_once('models/boletim.php');
fORM::mapClassToTable('Boletim', 'boletim');
include_once('models/tamanho_lotes.php');
fORM::mapClassToTable('TamanhoLotes', 'tamanho_lotes');
include_once('models/tipo_turma.php');
fORM::mapClassToTable('TipoTurma', 'tipo_turma');
include_once('models/condicao.php');
fORM::mapClassToTable('Condicao', 'condicao');
include_once('models/arredondamento.php');
fORM::mapClassToTable('Arredondamento', 'arredondamento');
include_once('models/componente.php');
fORM::mapClassToTable('Componente', 'componente');
include_once('models/motivos_desativacao.php');
fORM::mapClassToTable('MotivosDesativacao', 'motivo_desativacao');
include_once('models/tipo_condicao.php');
fORM::mapClassToTable('TipoCondicao', 'tipo_condicao');
include_once('models/curso_condicao.php');
fORM::mapClassToTable('CursoCondicao', 'curso_condicao');
include_once('models/curso_nota.php');
fORM::mapClassToTable('CursoNota', 'curso_nota');
include_once('models/curso_horario.php');
fORM::mapClassToTable('CursoHorario', 'curso_horario');

include_once('models/status_vaga.php');
fORM::mapClassToTable('StatusVaga', 'status_vaga');
include_once('models/vaga_pessoa.php');
fORM::mapClassToTable('VagaPessoa', 'vaga_pessoa');
include_once('models/vaga.php');
fORM::mapClassToTable('Vaga', 'vaga');
include_once('models/tipo_vaga.php');
fORM::mapClassToTable('TipoVaga', 'tipo_vaga');
include_once('models/faixa_salarial.php');
fORM::mapClassToTable('FaixaSalarial', 'faixa_salarial');
include_once('models/ramo_empresa.php');
fORM::mapClassToTable('RamoEmpresa', 'ramo_empresa');
include_once('models/empresa.php');
fORM::mapClassToTable('Empresa', 'empresa');
include_once('models/marcadores_vagas.php');
fORM::mapClassToTable('MarcadoresVagas', 'marcadores_vagas');
include_once('models/empresa_contato.php');
fORM::mapClassToTable('EmpresaContato', 'empresa_contato');
include_once('models/situacao_serie.php');
fORM::mapClassToTable('SituacaoSerie', 'situacao_serie');
include_once('models/historico_serie_diciplina.php');
fORM::mapClassToTable('HistoricoSerieDiciplina', 'historico_serie_diciplina');
include_once('models/historico_serie.php');
fORM::mapClassToTable('HistoricoSerie', 'historico_serie');

include_once('models/tipo_receita.php');
fORM::mapClassToTable('TipoReceita', 'tipo_receita');

include_once('models/motivo_bolsa.php');
fORM::mapClassToTable('MotivoBolsa', 'motivo_bolsa');
include_once('models/grupo_motivo_bolsa.php');
fORM::mapClassToTable('GrupoMotivoBolsa', 'grupo_motivo_bolsa');

include_once('models/tipo_carne.php');
fORM::mapClassToTable('TipoCarne', 'tipo_carne');
include_once('models/grupo_tipo_carne.php');
fORM::mapClassToTable('GrupoTipoCarne', 'grupo_tipo_carne');
include_once('models/situacao_matricula.php');
fORM::mapClassToTable('SituacaoMatricula', 'situacao_matricula');
include_once('models/matricula.php');
fORM::mapClassToTable('Matricula', 'matricula');
include_once('models/dia_semana.php');
fORM::mapClassToTable('DiaSemana', 'dia_semana');
include_once('models/grade_horario.php');
fORM::mapClassToTable('GradeHorario', 'grade_horario');
include_once('models/duracao_fase.php');
fORM::mapClassToTable('DuracaoFases', 'duracao_fases');
include_once('models/motorista.php');
fORM::mapClassToTable('Motorista', 'motorista');
include_once('models/veiculo_motorista.php');
fORM::mapClassToTable('VeiculoMotorista', 'veiculo_motorista');
include_once('models/bolsa.php');
fORM::mapClassToTable('Bolsa', 'bolsa');
include_once('models/aluno_financeiro.php');
fORM::mapClassToTable('AlunoFinanceiro', 'aluno_financeiro');
include_once('models/aluno_receita_fixa.php');
fORM::mapClassToTable('AlunoReceitaFixa', 'aluno_receita_fixa');
include_once('models/usuario.php');
fORM::mapClassToTable('Usuario', 'usuario');

include_once('models/veiculo.php');
fORM::mapClassToTable('Veiculo', 'veiculo');

include_once('models/rota.php');
fORM::mapClassToTable('Rota', 'rota');
include_once('models/itinerario.php');
fORM::mapClassToTable('Itinerario', 'rota_percurso');
include_once('models/rota_veiculo.php');
fORM::mapClassToTable('RotaVeiculo', 'rota_veiculo');
include_once('models/aluno_veiculo.php');
fORM::mapClassToTable('AlunoVeiculo', 'aluno_veiculo');
include_once('models/grade.php');
fORM::mapClassToTable('Grade', 'grade');
include_once('models/bloqueio_matricula.php');
fORM::mapClassToTable('BloqueioMatricula', 'bloqueio_matricula');
include_once('models/parametro_cobranca.php');
fORM::mapClassToTable('ParametroCobranca', 'parametro_cobranca');
include_once('models/parametro_cobranca_ocorrencia.php');
fORM::mapClassToTable('ParametroCobrancaOcorrencia', 'parametro_cobranca_ocorrencia');
include_once('models/cobranca_preco.php');
fORM::mapClassToTable('CobrancaPreco', 'cobranca_preco');
include_once('models/curso_complemento.php');
fORM::mapClassToTable('CursoComplemento', 'curso_complemento');
include_once('models/parcela.php');
fORM::mapClassToTable('Parcela', 'parcela');

include_once('models/situacao_ocorrencia.php');
fORM::mapClassToTable('SituacaoOcorrencia', 'situacao_ocorrencia');
include_once('models/grupo_tipo_avaliacao_periodica.php');
fORM::mapClassToTable('GrupoTipoAvaliacaoPeriodica', 'grupo_tipo_avaliacao_periodica');
include_once('models/tipo_avaliacao_periodica.php');
fORM::mapClassToTable('TipoAvaliacaoPeriodica', 'tipo_avaliacao_periodica');
include_once('models/tipo_itens_publicacao.php');
fORM::mapClassToTable('TipoItensPublicacao', 'tipo_itens_publicacao');
include_once('models/boleto_arquivo.php');
fORM::mapClassToTable('BoletoArquivo', 'boleto_arquivo');

include_once('models/evento_arquivo.php');
fORM::mapClassToTable('EventoArquivo', 'evento_arquivo');
include_once('models/falecido_causa_mortis.php');
fORM::mapClassToTable('FalecidoCausaMortis', 'falecido_causa_mortis');
include_once('models/tipo_plano_ua.php');
fORM::mapClassToTable('TipoPlanoUa', 'tipo_plano_ua');

include_once('models/sala_virtual.php');
fORM::mapClassToTable('SalaVirtual', 'sala_virtual');

include_once('models/sala_virtual_item.php');
fORM::mapClassToTable('SalaVirtualItem', 'sala_virtual_item');

include_once('models/categoria_sala_virtual.php');
fORM::mapClassToTable('CategoriaSalaVirtual', 'categoria_sala_virtual');

include_once('models/aulas.php');
fORM::mapClassToTable('Aulas', 'aulas');

include_once('models/ocorrencia_aula.php');
fORM::mapClassToTable('OcorrenciaAula', 'ocorrencia_aula');
include_once('models/ocorrencia_aluno.php');
fORM::mapClassToTable('OcorrenciaAluno', 'ocorrencia_aluno');
include_once('models/falta_aluno.php');
fORM::mapClassToTable('FaltaAluno', 'falta_aluno');
include_once('models/nota.php');
fORM::mapClassToTable('Nota', 'nota');
include_once('models/componente_detalhe.php');
fORM::mapClassToTable('ComponenteDetalhe', 'componente_detalhe');

include_once('models/comunicado.php');
fORM::mapClassToTable('Comunicado', 'comunicado');
include_once('models/comunicado_turma.php');
fORM::mapClassToTable('ComunicadoTurma', 'comunicado_turma');


include_once('models/sala_virtual_atribuicao.php');
fORM::mapClassToTable('SalaVirtualAtribuicao', 'sala_virtual_atribuicao');
include_once('models/sala_virtual_atribuicao_item.php');
fORM::mapClassToTable('SalaVirtualAtribuicaoItem', 'sala_virtual_atribuicao_item');

include_once('models/avaliacao_descritiva.php');
fORM::mapClassToTable('AvaliacaoDescritiva', 'avaliacao_descritiva');

include_once('models/avaliacao_periodica_aluno.php');
fORM::mapClassToTable('AvaliacaoPeriodicaAluno', 'avaliacao_periodica_aluno');

include_once('models/historico.php');
fORM::mapClassToTable('Historico', 'historico');
include_once('models/historico_item.php');
fORM::mapClassToTable('HistoricoItem', 'historico_item');
include_once('models/conversoes.php');
fORM::mapClassToTable('Conversoes', 'conversoes');

include_once('models/aluno_bloqueio.php');
fORM::mapClassToTable('AlunoBloqueio', 'aluno_bloqueio');
//outra maneira de incluir a model
//include_once('models/fid_use_sugestion.php'); //Nome do arquivo PHP que será criado
//fORM::mapClassToTable('fidUseSugestion', 'fid_use_sugestion'); //O primeiro parametro é o nome da Classe e o segundo parametro o nome da tabela
